# =========================================================================
# MODULE: Statistical Transformation & Outlier Engineering Engine
# =========================================================================
# Operational Context: Downstream of Feature Synthesis Layer.
# Purpose: Executes Winsorization outlier capping, applies multi-tier
#          mathematical transformations (Square Root, Box-Cox, Log1p) to
#          resolve severe skewness, and preserves true VIP customer identity
#          via passive shadow metadata tagging (Pattern 1).
#
# Architectural Strategy: Enforces numerical input domain safety gates, captures
#                         extreme behavioral outliers before value modification,
#                         and guarantees deterministic schema types for downstream scaling.
# =========================================================================

import logging
import numpy as np
import pandas as pd
from scipy.stats import boxcox

# Inherit the structured logging architecture established at the initialization root
logger = logging.getLogger(__name__)


def transform_and_remediate_outliers(
    df_rfm: pd.DataFrame, 
    capping_quantile: float = 0.99
) -> tuple[pd.DataFrame, float]:
    """
    Caps right-tail extreme outliers, normalizes feature distributions,
    and flags systemic high-value VIP cohorts before data transformation.
    
    Args:
        df_rfm (pd.DataFrame): Raw baseline RFM matrix from the feature engine.
        capping_quantile (float): Upper percentile threshold for Winsorization capping.
        
    Returns:
        tuple[pd.DataFrame, float]: 
            - pd.DataFrame: Memory-optimized, schema-locked feature and metadata matrix.
            - float: The optimized lambda parameter generated by the Box-Cox convergence sweep.
        
    Raises:
        KeyError: If mandatory behavioral features are missing from the input dataframe.
        ValueError: If input values violate numerical domain boundaries of the transformers.
        RuntimeError: If the mathematical optimization algorithm fails to converge.
    """
    logger.info("Initiating statistical normalization and outlier remediation engine...")

    # -------------------------------------------------------------------------
    # 1. PRE-CONDITION STRUCTURAL & MATHEMATICAL DOMAIN SAFETY GATES
    # -------------------------------------------------------------------------
    # FAIL-FAST PATTERN: Intercept structural deficits or illegal mathematical 
    # value states before initializing deep-copy allocations or optimization sweeps.
    # -------------------------------------------------------------------------
    required_cols = ['CustomerID', 'Recency', 'Frequency', 'Monetary']
    for col in required_cols:
        if col not in df_rfm.columns:
            logger.critical(f"Transformation Aborted: Missing required feature column: '{col}'")
            raise KeyError(f"Pipeline Interrupted: Missing column '{col}'")

    if (df_rfm['Recency'] < 0).any():
        logger.critical("Transformation Aborted: Recency contains negative entries.")
        raise ValueError("Mathematical Bound Violation: Recency must be non-negative for square root transformation.")

    if (df_rfm['Frequency'] <= 0).any():
        logger.critical("Transformation Aborted: Frequency contains non-positive values.")
        raise ValueError("Mathematical Bound Violation: Box-Cox transformation demands strictly positive values (> 0).")

    if (df_rfm['Monetary'] < 0).any():
        logger.critical("Transformation Aborted: Monetary contains negative values.")
        raise ValueError("Mathematical Bound Violation: Monetary must be non-negative for log1p stabilization.")

    # -------------------------------------------------------------------------
    # 2. RUNTIME DECOUPLING, VIP PRESERVATION, & ISOLATED WINSORIZATION
    # -------------------------------------------------------------------------
    # DESIGN PATTERN (PATTERN 1): Calculate right-tail boundaries and tag extreme 
    # value profiles *prior* to executing the capping array sequence. This preserves 
    # commercial VIP intelligence without distorting down-stream model coordinates.
    # -------------------------------------------------------------------------
    df_treated = df_rfm.copy(deep=True)
    capping_limits = {}

    # Capture raw mathematical cutoff thresholds
    freq_upper = df_treated['Frequency'].quantile(capping_quantile)
    monetary_upper = df_treated['Monetary'].quantile(capping_quantile)
    
    capping_limits['Frequency'] = freq_upper
    capping_limits['Monetary'] = monetary_upper

    # Generate shadow boolean flags to retain true identity metrics
    df_treated['Is_Frequency_Whale'] = (df_treated['Frequency'] > freq_upper).astype('int8')
    df_treated['Is_Monetary_Whale'] = (df_treated['Monetary'] > monetary_upper).astype('int8')
    df_treated['Is_Systemic_VIP'] = ((df_treated['Is_Frequency_Whale'] == 1) | 
                                     (df_treated['Is_Monetary_Whale'] == 1)).astype('int8')

    # Execute vectorized right-tail boundary clipping
    df_treated['Frequency'] = np.where(df_treated['Frequency'] > freq_upper, freq_upper, df_treated['Frequency'])
    df_treated['Monetary'] = np.where(df_treated['Monetary'] > monetary_upper, monetary_upper, df_treated['Monetary'])

    logger.info(f"Outlier Mitigation Applied: Frequency right-capped at {capping_limits['Frequency']:.1f} units.")
    logger.info(f"Outlier Mitigation Applied: Monetary right-capped at {capping_limits['Monetary']:.2f} value.")
    logger.info(f"VIP Preservation Locked: Identified {df_treated['Is_Systemic_VIP'].sum()} systemic whale profiles.")

    # -------------------------------------------------------------------------
    # 3. MULTI-AXIS NON-LINEAR VECTOR TRANSFORMS
    # -------------------------------------------------------------------------
    # COMPUTE EXECUTION: Matches mathematical transformations directly to the 
    # structural skew profile of each target attribute.
    # -------------------------------------------------------------------------
    logger.info("Executing vectorized non-linear transformations across feature space...")
    
    recency_transformed = np.sqrt(df_treated['Recency'])
    monetary_transformed = np.log1p(df_treated['Monetary'])

    # Safely isolate Box-Cox calculation inside an optimization tracking block
    try:
        freq_transformed, raw_lambda = boxcox(df_treated['Frequency'])
        lambda_val = float(raw_lambda)  # Ensure standard python float serialization compatibility
    except Exception as opt_error:
        logger.critical(f"Mathematical Optimization Failure: Box-Cox failed to converge. Details: {str(opt_error)}")
        raise RuntimeError(f"Pipeline Optimization Aborted: Box-Cox estimation error: {str(opt_error)}")

    logger.info(f"Optimal Box-Cox Lambda parameter calculated for Frequency: {lambda_val:.4f}")

    # -------------------------------------------------------------------------
    # 4. TARGET FRAME ASSEMBLY & SCHEMA CONSTRAINTS
    # -------------------------------------------------------------------------
    # DESIGN PATTERN: Assembles a dedicated tracking dataframe with clean explicit 
    # indexing, standardizes naming layouts, and compresses storage footprint lengths.
    # -------------------------------------------------------------------------
    df_rfm_transformed = pd.DataFrame(index=df_treated.index)
    df_rfm_transformed['CustomerID'] = df_treated['CustomerID']
    
    # Clustering Features
    df_rfm_transformed['Recency_sqrt'] = recency_transformed
    df_rfm_transformed['Frequency_boxcox'] = freq_transformed
    df_rfm_transformed['Monetary_log'] = monetary_transformed
    
    # Shadow Metadata Flags
    df_rfm_transformed['Is_Systemic_VIP'] = df_treated['Is_Systemic_VIP']

    # Enforce strict coordinate alignment
    target_columns = ['CustomerID', 'Recency_sqrt', 'Frequency_boxcox', 'Monetary_log', 'Is_Systemic_VIP']
    df_rfm_transformed = df_rfm_transformed[target_columns]

    schema_lock = {
        'CustomerID': 'int32',
        'Recency_sqrt': 'float32',
        'Frequency_boxcox': 'float32',
        'Monetary_log': 'float32',
        'Is_Systemic_VIP': 'int8'
    }
    df_rfm_transformed = df_rfm_transformed.astype(schema_lock)

    # -------------------------------------------------------------------------
    # 5. POST-CONDITION INTEGRITY CONTRACT ASSERTERS
    # -------------------------------------------------------------------------
    # DEFENSIVE CHECKPOINT: Verifies structural transformation health before passing 
    # coordinate arrays to downstream standard distance scaling engines.
    # -------------------------------------------------------------------------
    try:
        assert df_rfm_transformed.shape[0] == df_rfm.shape[0], "Contract Breach: Observation count shifted during transformation."
        assert df_rfm_transformed.notnull().all().all(), "Contract Breach: Uncaught NaN allocations introduced during transformation."
        
        # Verify infinity constraints strictly over numerical modeling coordinates
        modeling_features = ['Recency_sqrt', 'Frequency_boxcox', 'Monetary_log']
        assert np.isfinite(df_rfm_transformed[modeling_features]).all().all(), "Contract Breach: Infinite coordinate values detected."
    except AssertionError as contract_error:
        logger.critical(f"Transformation Target Contract Failure: {str(contract_error)}")
        raise contract_error

    logger.info("Statistical stabilization engineering completed successfully.")
    return df_rfm_transformed, lambda_val


# =========================================================================
# 6. PIPELINE RUNTIME ENTRY POINT
# =========================================================================
if __name__ == "__main__":
    logger.info("Transformation engine module loaded standalone. System idling.")